### ISSUE TITLE
The Travis build of this package depends on bob.blitz which depends on this one

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.extension#7]
It is a bit weird that, for testing this package, we require bob.blitz which, in turn, requires this one to be built. Would it be possible to untangle these things? This does not very well in all conditions (e.g. Conda builds)

**Comment by siebenkopf** [comment]
I don't see a direct problem in this, maybe you can tell me a bit more about, how the Conda builds are failing?

Indeed, there is a circular dependency of the tow packages, but only in test time, and only for some of the tests. The issue is that we have stored ``bob.example.package``, ``bob.example.extension`` and ``bob.example.library`` inside this package, and only the test for ``bob.example.extension`` and ``bob.example.library`` rely on ``bob.blitz``. Anyways, I don't see a direct problem, as these tests actually download ``bob.blitz`` from PyPI if it is not installed -- if it does not, then we have to correct the test cases.

**Comment by anjos** [comment]
It makes it a circular dependence. In a thorough system like conda, you need to build and test a package before you can install the next one. So, bob.extension gets build and, when it will be tested, it requires a package that has not been built yet.

**Comment by siebenkopf** [comment]
Hmm... but the test does not require ``bob.blitz`` to be built before. The test downloads a ``bob.example.extension`` to a temporary directory in ``/tmp``, and tries to build it. During the build, ``bob.blitz`` gets downloaded from PyPI and installed in ``/tmp``, where it uses this ``bob.extension`` package. After the build finishes, the ``bob.blitz`` build is deleted again.

Could you please tell me, which part of this test fails? Could you provide me with a detailed error message?

**Comment by anjos** [comment]
I guess this is a no-issue anymore, after @183amir solved the packaging for conda. Apologies for the noise!

**Comment by 183amir** [comment]
This is fixed by not running some tests.

**Comment by 183amir** [comment]
This is a problem because downloading from PyPI is disabled during conda builds and tests

**Comment by anjos** [comment]
This test is disabled everytime we need to do a binary build.

**Comment by siebenkopf** [comment]
I don't see any commit for this? Did you find another way to disable the tests?

**Comment by anjos** [comment]
It is a command-line option to `nosetests`, so it is manageable through the packaging script.
